### ISSUE TITLE
MP Config: add some tests for type conversions

### ISSUE THREAD

**Issue by Ladicek** [rhoar-qe/thorntail-test-suite#23]
We currently almost don't test type conversions, with one exception (to a `long`). We should add some. Default converters prescribed by MP Config allow converting to

- `boolean` and `Boolean`
- `int` and `Integer`
- `long` and `Long`
- `float` and `Float`
- `double` and `Double`
- `Class` (based on `Class.forName`)

We should also add a test for some custom converter (best to our custom class).

Conversion to arrays (and, in case of `@Inject`-ing a `@ConfigProperty`, also `List`s and `Set`s) of otherwise supported values (built-in and custom converters) is also supported and should be tested.

It seems the MP Config TCK does a pretty good job, so this should be more of a smoke test.

**Comment by penehyba** [comment]
@Ladicek Cau you please update this issue? There are some modification in 1.3 and new tests:
[CDIPlainInjectionTest.java#L108](https://github.com/eclipse/microprofile-config/blob/8839aa69b6a87f196d1a22dc0c965851173351e2/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java#L108)
[testImplicitConverterStringOf()](https://github.com/eclipse/microprofile-config/commit/611a915b5086ba34c2538d1fb9b9dbfb53986755)

**Comment by Ladicek** [comment]
@penehyba This issue is about adding tests to this repo. If you think there's more tests missing in this repo, feel free to indicate that in a comment, or create another issue.
